name: Lint & Test

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  Lint:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn tsc
      - name: Cleanup
        if: ${{ always() }}
        run: |
          shopt -s dotglob
          rm -rf *

  Test:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Install Dependencies
        run: yarn
      - name: Set up Git
        run: |
          git config --global init.defaultBranch main
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      - name: Test
        run: yarn test:once
      - name: Cleanup
        if: ${{ always() }}
        run: |
          shopt -s dotglob
          rm -rf *
