name: Lint & Test

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  Lint:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cache node_modules
        uses: actions/cache@v3.2.3
        env:
          cache-name: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn-lock.json') }}
      - name: Install dependencies
        run: |
          if [ ! -d node_modules ]; then
            yarn
          fi
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn tsc
      - name: Cleanup
        if: ${{ always() }}
        run: |
          shopt -s dotglob
          rm -rf *

  Test:
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cache node_modules
        uses: actions/cache@v3.2.3
        env:
          cache-name: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn-lock.json') }}
      - name: Install dependencies
        run: |
          if [ ! -d node_modules ]; then
            yarn
          fi
      - name: Test
        run: yarn test:once
      - name: Cleanup
        if: ${{ always() }}
        run: |
          shopt -s dotglob
          rm -rf *
